In [1]:
import pandas as pd
import numpy as np
df=pd.read_csv(r'D:/2016-FCC-New-Coders-Survey-Data.csv',usecols=['CityPopulation','EmploymentStatus','Gender','HasDebt','JobPref','JobWherePref','MaritalStatus','Income','SchoolDegree'])

In [2]:
df

,CityPopulation,EmploymentStatus,Gender,HasDebt,Income,JobPref,JobWherePref,MaritalStatus,SchoolDegree
0,"between 100,000 and 1 million",Employed for wages,male,1.0,32000.0,freelance,NaN,married or domestic partnership,"some college credit, no degree"
1,"between 100,000 and 1 million",Employed for wages,male,0.0,15000.0,work for a startup,in an office with other developers,NaN,"some college credit, no degree"
2,more than 1 million,Employed for wages,male,0.0,48000.0,start your own business,NaN,NaN,high school diploma or equivalent (GED)
3,more than 1 million,Employed for wages,female,1.0,43000.0,work for a startup,from home,NaN,bachelor's degree
4,"between 100,000 and 1 million",Employed for wages,female,1.0,6000.0,work for a medium-sized company,in an office with other developers,NaN,"some college credit, no degree"
...,...,...,...,...,...,...,...,...,...
15615,more than 1 million,Self-employed freelancer,male,1.0,10000.0,start your own business,NaN,"single, never married",bachelor's degree
15616,more than 1 million,Employed for wages,male,0.0,10000.0,work for a startup,in an office with other developers,"single, never married",bachelor's degree
15617,more than 1 million,Self-employed freelancer,male,0.0,48000.0,freelance,NaN,NaN,bachelor's degree
15618,more than 1 million,Self-employed freelancer,male,0.0,10000.0,NaN,NaN,NaN,master's degree (non-professional)
15619,more than 1 million,Employed for wages,female,1.0,18000.0,freelance,NaN,"single, never married",bachelor's degree

In [3]:
df=df.dropna()
df=df[(df.Gender=='male')|(df.Gender=='female')]

In [4]:
df

,CityPopulation,EmploymentStatus,Gender,HasDebt,Income,JobPref,JobWherePref,MaritalStatus,SchoolDegree
20,more than 1 million,Employed for wages,female,1.0,200000.0,work for a medium-sized company,in an office with other developers,married or domestic partnership,master's degree (non-professional)
36,"between 100,000 and 1 million",Self-employed freelancer,male,1.0,60000.0,work for a medium-sized company,in an office with other developers,married or domestic partnership,high school diploma or equivalent (GED)
59,more than 1 million,Employed for wages,male,1.0,35000.0,work for a medium-sized company,in an office with other developers,married or domestic partnership,"some college credit, no degree"
71,more than 1 million,Employed for wages,male,1.0,56000.0,work for a multinational corporation,from home,married or domestic partnership,"some college credit, no degree"
72,"less than 100,000",Employed for wages,male,1.0,35000.0,work for a medium-sized company,from home,married or domestic partnership,bachelor's degree
...,...,...,...,...,...,...,...,...,...
15564,"less than 100,000",Employed for wages,male,1.0,200000.0,work for a medium-sized company,in an office with other developers,married or domestic partnership,"professional degree (MBA, MD, JD, etc.)"
15566,more than 1 million,Employed for wages,male,0.0,200000.0,work for a startup,no preference,married or domestic partnership,bachelor's degree
15584,more than 1 million,Employed for wages,male,1.0,200000.0,work for a multinational corporation,in an office with other developers,married or domestic partnership,bachelor's degree
15598,"less than 100,000",Employed for wages,male,1.0,200000.0,work for a medium-sized company,from home,married or domestic partnership,associate's degree
15616,more than 1 million,Employed for wages,male,0.0,10000.0,work for a startup,in an office with other developers,"single, never married",bachelor's degree

In [5]:
import scipy.stats as stats
stats.shapiro(df.Income)
stats.shapiro(df.Income.apply(lambda x: np.log(x)))
stats.shapiro(df.Income[0:100].apply(lambda x: np.log(x)))
df2=df.iloc[0:100,:].copy()
df2.Income=df2.Income.apply(lambda x: np.log(x))
from statsmodels.formula.api import ols
model = ols('Income ~ SchoolDegree',df).fit()
model.summary()
model = ols('Income ~ SchoolDegree',df2).fit()
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                 Income   R-squared:                       0.062
Model:                            OLS   Adj. R-squared:                 -0.031
Method:                 Least Squares   F-statistic:                    0.6649
Date:                Wed, 10 Apr 2024   Prob (F-statistic):              0.738
Time:                        19:20:06   Log-Likelihood:                -103.19
No. Observations:                 100   AIC:                             226.4
Df Residuals:                      90   BIC:                             252.4
Df Model:                           9
Covariance Type:            nonrobust
============================================================================================================================
                                                               coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------------------------------------------------
Intercept                                                   10.5784      0.358     29.557      0.000       9.867      11.289
SchoolDegree[T.associate's degree]                          -0.5535      0.449     -1.234      0.221      -1.445       0.338
SchoolDegree[T.bachelor's degree]                            0.0928      0.378      0.246      0.807      -0.658       0.843
SchoolDegree[T.high school diploma or equivalent (GED)]     -0.1376      0.438     -0.314      0.754      -1.008       0.733
SchoolDegree[T.master's degree (non-professional)]          -0.0493      0.396     -0.125      0.901      -0.835       0.737
SchoolDegree[T.no high school (secondary school)]            0.5037      0.800      0.629      0.531      -1.086       2.094
SchoolDegree[T.professional degree (MBA, MD, JD, etc.)]      0.0968      0.438      0.221      0.826      -0.774       0.968
SchoolDegree[T.some college credit, no degree]               0.0135      0.413      0.033      0.974      -0.808       0.835
SchoolDegree[T.some high school]                            -0.1870      0.547     -0.342      0.733      -1.273       0.899
SchoolDegree[T.trade, technical, or vocational training]     0.0552      0.506      0.109      0.913      -0.950       1.061
==============================================================================
Omnibus:                        1.322   Durbin-Watson:                   1.865
Prob(Omnibus):                  0.516   Jarque-Bera (JB):                1.298
Skew:                          -0.268   Prob(JB):                        0.523
Kurtosis:                       2.846   Cond. No.                         18.2
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [7]:
from statsmodels.stats.multicomp import pairwise_tukeyhsd, MultiComparison
mc=MultiComparison(df2.Income,df2.SchoolDegree)
print(mc.tukeyhsd())

                                 Multiple Comparison of Means - Tukey HSD, FWER=0.05
======================================================================================================================
                 group1                                  group2                  meandiff p-adj   lower  upper  reject
----------------------------------------------------------------------------------------------------------------------
                                  Ph.D.                       associate's degree  -0.5535    0.9 -2.0091  0.902  False
                                  Ph.D.                        bachelor's degree   0.0928    0.9 -1.1329 1.3185  False
                                  Ph.D.  high school diploma or equivalent (GED)  -0.1376    0.9 -1.5597 1.2845  False
                                  Ph.D.       master's degree (non-professional)  -0.0493    0.9  -1.333 1.2344  False
                                  Ph.D.        no high school (secondary school)   0.5037    0.9 -2.0927 3.1001  False
                                  Ph.D.  professional degree (MBA, MD, JD, etc.)   0.0968    0.9 -1.3253 1.5189  False
                                  Ph.D.           some college credit, no degree   0.0135    0.9 -1.3273 1.3543  False
                                  Ph.D.                         some high school   -0.187    0.9 -1.9606 1.5867  False
                                  Ph.D. trade, technical, or vocational training   0.0552    0.9 -1.5869 1.6973  False
                     associate's degree                        bachelor's degree   0.6463  0.479 -0.3152 1.6078  False
                     associate's degree  high school diploma or equivalent (GED)    0.416    0.9 -0.7859 1.6179  False
                     associate's degree       master's degree (non-professional)   0.5042 0.8376 -0.5302 1.5387  False
                     associate's degree        no high school (secondary school)   1.0573    0.9 -1.4253 3.5399  False
                     associate's degree  professional degree (MBA, MD, JD, etc.)   0.6503 0.7337 -0.5516 1.8522  False
                     associate's degree           some college credit, no degree    0.567 0.7874 -0.5374 1.6715  False
                     associate's degree                         some high school   0.3666    0.9  -1.236 1.9691  False
                     associate's degree trade, technical, or vocational training   0.6088    0.9 -0.8468 2.0644  False
                      bachelor's degree  high school diploma or equivalent (GED)  -0.2303    0.9 -1.1404 0.6797  False
                      bachelor's degree       master's degree (non-professional)  -0.1421    0.9 -0.8157 0.5315  False
                      bachelor's degree        no high school (secondary school)   0.4109    0.9 -1.9443 2.7662  False
                      bachelor's degree  professional degree (MBA, MD, JD, etc.)    0.004    0.9 -0.9061 0.9141  False
                      bachelor's degree           some college credit, no degree  -0.0793    0.9 -0.8562 0.6975  False
                      bachelor's degree                         some high school  -0.2798    0.9 -1.6768 1.1173  False
                      bachelor's degree trade, technical, or vocational training  -0.0375    0.9 -1.2632 1.1881  False
high school diploma or equivalent (GED)       master's degree (non-professional)   0.0882    0.9 -0.8985  1.075  False
high school diploma or equivalent (GED)        no high school (secondary school)   0.6413    0.9 -1.8219 3.1044  False
high school diploma or equivalent (GED)  professional degree (MBA, MD, JD, etc.)   0.2343    0.9 -0.9268 1.3955  False
high school diploma or equivalent (GED)           some college credit, no degree    0.151    0.9 -0.9089  1.211  False
high school diploma or equivalent (GED)                         some high school  -0.0494    0.9 -1.6216 1.5228  False
high school diploma or equivalent (GED) trade, technical, or vocational training   0.1928    0.9 -1.2293 1.6149  False
     master's degree (non-professional)        no high school (secondary school)    0.553    0.9 -1.8329  2.939  False
     master's degree (non-professional)  professional degree (MBA, MD, JD, etc.)   0.1461    0.9 -0.8407 1.1329  False
     master's degree (non-professional)           some college credit, no degree   0.0628    0.9 -0.8027 0.9283  False
     master's degree (non-professional)                         some high school  -0.1377    0.9 -1.5859 1.3105  False
     master's degree (non-professional) trade, technical, or vocational training   0.1046    0.9 -1.1791 1.3882  False
      no high school (secondary school)  professional degree (MBA, MD, JD, etc.)  -0.4069    0.9 -2.8701 2.0562  False
      no high school (secondary school)           some college credit, no degree  -0.4902    0.9 -2.9074 1.9269  False
      no high school (secondary school)                         some high school  -0.6907    0.9 -3.3723 1.9908  False
      no high school (secondary school) trade, technical, or vocational training  -0.4485    0.9 -3.0449 2.1479  False
professional degree (MBA, MD, JD, etc.)           some college credit, no degree  -0.0833    0.9 -1.1433 0.9767  False
professional degree (MBA, MD, JD, etc.)                         some high school  -0.2838    0.9  -1.856 1.2884  False
professional degree (MBA, MD, JD, etc.) trade, technical, or vocational training  -0.0415    0.9 -1.4636 1.3806  False
         some college credit, no degree                         some high school  -0.2005    0.9 -1.6995 1.2986  False
         some college credit, no degree trade, technical, or vocational training   0.0418    0.9  -1.299 1.3825  False
                       some high school trade, technical, or vocational training   0.2422    0.9 -1.5315 2.0159  False
----------------------------------------------------------------------------------------------------------------------

In [8]:
model = ols('Income ~ SchoolDegree + Gender + MaritalStatus + CityPopulation + EmploymentStatus + JobPref + JobWherePref',df2).fit()
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                 Income   R-squared:                       0.145
Model:                            OLS   Adj. R-squared:                 -0.072
Method:                 Least Squares   F-statistic:                    0.6695
Date:                Wed, 10 Apr 2024   Prob (F-statistic):              0.844
Time:                        19:21:02   Log-Likelihood:                -98.581
No. Observations:                 100   AIC:                             239.2
Df Residuals:                      79   BIC:                             293.9
Df Model:                          20
Covariance Type:            nonrobust
============================================================================================================================
                                                               coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------------------------------------------------
Intercept                                                   10.6129      0.582     18.248      0.000       9.455      11.771
SchoolDegree[T.associate's degree]                          -0.4325      0.482     -0.898      0.372      -1.392       0.527
SchoolDegree[T.bachelor's degree]                            0.1028      0.400      0.257      0.798      -0.693       0.899
SchoolDegree[T.high school diploma or equivalent (GED)]      0.0323      0.463      0.070      0.945      -0.890       0.954
SchoolDegree[T.master's degree (non-professional)]           0.1161      0.427      0.272      0.786      -0.733       0.965
SchoolDegree[T.no high school (secondary school)]            1.1166      0.893      1.250      0.215      -0.661       2.895
SchoolDegree[T.professional degree (MBA, MD, JD, etc.)]      0.3029      0.473      0.640      0.524      -0.640       1.245
SchoolDegree[T.some college credit, no degree]               0.1309      0.437      0.300      0.765      -0.739       1.001
SchoolDegree[T.some high school]                            -0.0188      0.575     -0.033      0.974      -1.163       1.125
SchoolDegree[T.trade, technical, or vocational training]     0.0289      0.539      0.054      0.957      -1.045       1.103
Gender[T.male]                                               0.0003      0.209      0.002      0.999      -0.416       0.417
MaritalStatus[T.married or domestic partnership]            -0.0394      0.358     -0.110      0.913      -0.751       0.673
MaritalStatus[T.single, never married]                       0.1060      0.445      0.238      0.812      -0.779       0.991
CityPopulation[T.less than 100,000]                          0.0364      0.204      0.179      0.859      -0.369       0.442
CityPopulation[T.more than 1 million]                       -0.2315      0.193     -1.201      0.233      -0.615       0.152
EmploymentStatus[T.Self-employed business owner]             0.5196      0.355      1.464      0.147      -0.187       1.226
EmploymentStatus[T.Self-employed freelancer]                -0.4856      0.338     -1.438      0.154      -1.158       0.187
JobPref[T.work for a multinational corporation]              0.1250      0.246      0.507      0.613      -0.365       0.615
JobPref[T.work for a startup]                                0.1088      0.208      0.523      0.602      -0.305       0.523
JobWherePref[T.in an office with other developers]          -0.0827      0.169     -0.489      0.626      -0.420       0.254
JobWherePref[T.no preference]                               -0.0902      0.263     -0.343      0.733      -0.613       0.433
==============================================================================
Omnibus:                        0.781   Durbin-Watson:                   1.744
Prob(Omnibus):                  0.677   Jarque-Bera (JB):                0.460
Skew:                          -0.155   Prob(JB):                        0.794
Kurtosis:                       3.122   Cond. No.                         32.3
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""